// Crea el esquema completo de Credenza en Supabase (PostgreSQL).
// Ejecutar una vez: node backend/setup_db.js
const { pool } = require('./db');

const DDL = `
create table if not exists "Roles" (
  "Id"     bigint generated by default as identity primary key,
  "Nombre" varchar(100) not null
);

create table if not exists "Usuarios" (
  "Id"                 bigint generated by default as identity primary key,
  "Nombre"             varchar(150) not null,
  "Apellido"           varchar(150),
  "Email"              varchar(255) not null unique,
  "ContrasenaHash"     varchar(255) not null,
  "Ciudad"             varchar(150),
  "RolId"              bigint not null default 1 references "Roles"("Id"),
  "Activo"             boolean not null default true,
  "Perfil"             jsonb,
  "FechaCreacion"      timestamptz not null default now(),
  "FechaActualizacion" timestamptz not null default now()
);

create table if not exists "HistorialAnalisis" (
  "Id"                    bigint generated by default as identity primary key,
  "UsuarioId"             bigint not null references "Usuarios"("Id") on delete cascade,
  "ProductoNombre"        varchar(255) not null,
  "ProductoPrecio"        numeric(18,2) not null default 0,
  "ProductoCategoria"     varchar(100),
  "RecomendacionScore"    numeric(5,2) not null default 0,
  "Viable"                boolean not null default false,
  "MensajeSugerencia"     text,
  "ResultadoCompletoJSON" jsonb,
  "FechaAnalisis"         timestamptz not null default now()
);
create index if not exists "IX_Historial_Usuario_Fecha"
  on "HistorialAnalisis" ("UsuarioId", "FechaAnalisis" desc);

create table if not exists "SegmentosFinancierosUsuario" (
  "Id"                 bigint generated by default as identity primary key,
  "UsuarioId"          bigint not null references "Usuarios"("Id") on delete cascade,
  "SegmentId"          integer not null,
  "SegmentName"        varchar(255) not null,
  "ProfileScore"       numeric(5,2) not null default 0,
  "Summary"            varchar(500),
  "FechaCreacion"      timestamptz not null default now(),
  "FechaActualizacion" timestamptz not null default now()
);
create unique index if not exists "UQ_Segmentos_Usuario"
  on "SegmentosFinancierosUsuario" ("UsuarioId");

insert into "Roles" ("Id","Nombre")
values (1,'Usuario'), (2,'Admin')
on conflict ("Id") do nothing;
`;

(async () => {
    try {
        await pool.query(DDL);
        const t = await pool.query(
            `select table_name from information_schema.tables where table_schema='public' order by table_name`
        );
        console.log('OK - Esquema creado en Supabase. Tablas:',
            t.rows.map(r => r.table_name).join(', '));
    } catch (e) {
        console.error('Error creando el esquema:', e.message);
        process.exitCode = 1;
    } finally {
        await pool.end();
    }
})();
